spring:
  application:
    name: LearningTrialBookingJPA
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/LtJPAApplication?createDatabaseIfNotExist=true
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

